[project]
name = "leonid"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "ruff>=0.8.1",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
]

[dependency-groups]
dev = [
    "ruff>=0.8.1",
]
